### ISSUE TITLE
Error: Cannot find module 'storybook/internal/common' after upgrading from v8 to v9

### ISSUE THREAD

**Issue by byleth40k** [storybookjs/react-native#805]
**Describe the bug**
I upgraded Storybook on an Expo React native app (No expo router) from v8 (working fine) to v9 but got the following error when trying to run the script for storybook-generate
`Error: Cannot find module 'storybook/internal/common'`

**To Reproduce**
I dont know how to give you steps to reproduce it, bu I was following the migration guide, so I updated the `@storybook/react-native` and the `addons` packages to their latest versions, renamed `.storybook` to `.rnstorybook` and changed the app entry to reflect that folder name change and then tried to re-generate the `storybook.requires.ts` file, but got that error. This happened sadly on a private repo, so i cant share it either.

**Expected behavior**
It should let me regenerate the file and then open storybook normally

**System:**
  System:
    OS: macOS 26.0.1
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.2 - ~/.local/state/fnm_multishells/76443_1761254045931/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn <----- active
    npm: 10.8.2 - ~/.local/state/fnm_multishells/76443_1761254045931/bin/npm
    pnpm: 10.18.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 26.0.1
  npmPackages:
    @storybook/react-native: ^8.4.3 => 9.1.4 
    eslint-plugin-storybook: 9.1.10 => 9.1.10 

**Additional context**
I already rolled back to v8 because I need to finish some stuff, but can share more info later if needed.

**Comment by dannyhw** [comment]
Make sure you update all storybook packages and that you have the "storybook" package installed

**Comment by byleth40k** [comment]
> Make sure you update all storybook packages and that you have the "storybook" package installed

I did, I have the `@storybook/react-native package` and the `@storybook/addon-ondevice-controls` and `@storybook/addon-ondevice-actions` all updated to their latest versions when I got that error.

**Comment by dannyhw** [comment]
What about specifically the `storybook` package, its a peer dependency for the other packages.

Also make sure you have the withStorybook metro wrapper applied.

Maybe you could share more of your package.json, metro config etc

**Comment by byleth40k** [comment]
oh I didnt notice that I needed the storybook package! I had just those 3 previously with v8 and just updated those! Big thanks, is working perfectly now that I added it, sorry for the confusion!

**Comment by dannyhw** [comment]
No problem, glad that its working now 😁
